<?php

namespace Ernestre\PaymentBundle\Repository;

/**
 * SmsPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SmsPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
